apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: 837126493345.dkr.ecr.ap-northeast-2.amazonaws.com/goormthon-6/frontend:build-17
